---
- name: ensure required mysql packages are installed
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - mysql-server
    - python-mysqldb

- name: ensure mysql is started and enabled
  service: 
    name: mysql 
    state: started 
    enabled: yes

- name: update mysql root password for all root accounts
  mysql_user: 
    name: root 
    host: localhost 
    password: "{{ diaspora_root_mysql_password }}"

# Need to do this for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: copy .my.cnf file with root password credentials
  template: 
    src: root/.my.cnf 
    dest: /root/.my.cnf 
    owner: root 
    group: root 
    mode: 0600

- name: update mysql root password for all root accounts
  mysql_user: 
    name: root 
    host: "{{ item }}" 
    password: "{{ diaspora_root_mysql_password }}" 
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1

- name: ensure anonymous users are not in the database
  mysql_user: 
    name: "" 
    host: "{{ item }}"
    state: absent
  with_items:
    - "{{ ansible_hostname }}"
    - "{{ inventory_hostname }}"
    - localhost
    - 127.0.0.1
    - ::1
    - "%"
